import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRef } from "react";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="flex justify-center">
          <div className="absolute bottom-8">
            <Navbar />
          </div>
        </div>
      </body>
    </html>
  );
}
